on:
    pull_request:
      branches:
        - main
      types: ["closed"]
  
jobs:
    cherry_pick_release_v1_0:
      runs-on: ubuntu-latest
      name: Cherry pick into release-v1.0
      if: ${{ contains(github.event.pull_request.labels.*.name, 'release-v1.0') && github.event.pull_request.merged == true }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Cherry pick into release-v1.0
          uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
          with:
            branch: release-v1.0
            labels: |
              cherry-pick
env:
    GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
